### PR TITLE
Fix: `InvoiceLine` tax validation issues

### LINKED ISSUE #24: InvoiceLine tax validation issues
Identified issues with InvoiceLine tax validation.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #24

### CODE REVIEW

File: ubl/Handlers/Invoice/InvoiceLineHandler.php [hunk 1]
```diff
@@ -12,52 +12,67 @@
...
 	public function handle( $data, $options = array() ) {
-		$items      = $this->document->order->get_items( array( 'line_item', 'fee', 'shipping' ) );
-		$taxReasons = TaxesSettings::get_available_reasons();
+		$items        = $this->document->order->get_items( array( 'line_item', 'fee', 'shipping' ) );
+		$taxReasons   = TaxesSettings::get_available_reasons();
+		$orderTaxData = $this->document->order_tax_data;
 
 		// Build the tax totals array
 		foreach ( $items as $item_id => $item ) {
 			$taxSubtotal      = array();
```
Comment (MohamadNateqi) [inline ubl/Handlers/Invoice/InvoiceLineHandler.php]: Where is this array used? I only see its value is updated!

Comment (alexmigf) [reply ubl/Handlers/Invoice/InvoiceLineHandler.php]: Good catch! Fixed.

File: ubl/Handlers/Invoice/InvoiceLineHandler.php [hunk 2]
```diff
@@ -12,88 +12,42 @@
...
-						'name'  => 'cbc:TaxExemptionReason',
-						'value' => $reason,
-					);
-				}
+			foreach ( $itemTaxData as $tax_id => $tax ) {
+				$itemTaxData       = ! empty( $orderTaxData[ $tax_id ] )         ? $orderTaxData[ $tax_id ]         : $itemTaxData;
+				$itemTaxPercentage = ! empty( $itemTaxData['percentage'] )       ? $itemTaxData['percentage']       : 0;
+				$itemTaxCategory   = ! empty( $itemTaxData['category'] )         ? $itemTaxData['category']         : wpo_ips_ubl_get_tax_data_from_fallback( 'category', null );
+				$itemTaxReasonKey  = ! empty( $itemTaxData['reason'] )           ? $itemTaxData['reason']           : wpo_ips_ubl_get_tax_data_from_fallback( 'reason', null );
+				$itemTaxReason     = ! empty( $taxReasons[ $itemTaxReasonKey ] ) ? $taxReasons[ $itemTaxReasonKey ] : $itemTaxReasonKey;
```
Comment (MohamadNateqi) [inline ubl/Handlers/Invoice/InvoiceLineHandler.php]: Not used

File: ubl/Handlers/Invoice/InvoiceLineHandler.php [hunk 3]
```diff
@@ -12,88 +12,42 @@
...
-								'currencyID' => $this->document->order->get_currency(),
-							),
-						),
-						array(
-							'name'  => 'cac:TaxCategory',
-							'value' => $taxCategory,
-						),
-					),
+				// Rebuild the item tax data to be used by 'ClassifiedTaxCategory'
+				$itemTaxData = array(
```
Comment (MohamadNateqi) [inline ubl/Handlers/Invoice/InvoiceLineHandler.php]: The `foreach ( $itemTaxData as $tax_id => $tax ) {` executes, and the `$itemTaxData` only keeps values from the last step of this loop, and then it'll be used in the bottom lines for `ClassifiedTaxCategory`.

It seems a little strange to me. Do we need to display data from all of the items of the loop? 
If the data for the last item is only necessary, then I think there is no need for a loop?

I don't know the correct data structure here, but I'm a little confused!

**Review by MohamadNateqi — CHANGES_REQUESTED** [review]

File: ubl/Handlers/Invoice/InvoiceLineHandler.php [hunk 4]
```diff
@@ -12,88 +11,39 @@
...
+			$itemTaxData           = isset( $item[ $taxDataContainer ][ $taxDataKey ] ) ? $item[ $taxDataContainer ][ $taxDataKey ] : array();
+			$multipleTaxCategories = array();
+			
+			// Fallback if no tax data is available
+			if ( empty( $itemTaxData ) ) {
+				$itemTaxData = array(
+					0 => array(
+						'percentage' => 0,
+						'category'   => '',
+						'reason'     => '',
```
Comment (MohamadNateqi) [inline ubl/Handlers/Invoice/InvoiceLineHandler.php]: I think this can be removed.

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
